export const providerList = [
  { value: 0, label: 'Bypass' },
  { value: 1, label: 'Mirket Token' },
  { value: 2, label: 'Mirket OTP' },
  { value: 3, label: 'Mirket Push' },
  { value: 4, label: 'TOTP' },
  { value: 5, label: 'NON1' },
  { value: 6, label: 'NON1' },
  { value: 7, label: 'NON1' },
  { value: 8, label: 'NON1' },
  { value: 9, label: 'NON1' },
  { value: 10, label: 'NON1' },
  { value: 11, label: 'NON1' },
  { value: 12, label: 'NON1' },
  { value: 13, label: 'NON1' },
  { value: 14, label: 'NON1' },
  { value: 15, label: 'AsistBT' },
  { value: 16, label: 'Fast SMS' },
  { value: 17, label: 'Jet SMS' },
  { value: 18, label: 'Jet SMS QUERY' },
  { value: 19, label: 'Jet SMS QUERY v2' },
  { value: 20, label: 'Maradit' },
  { value: 21, label: 'Mobildev' },
  { value: 22, label: 'Mobildev v2' },
  { value: 23, label: 'Netgsm' },
  { value: 24, label: 'Posta Guvercini' },
  { value: 25, label: 'Smile SMS' },
  { value: 26, label: 'Teknomart' },
  { value: 27, label: 'Teknomart OTP' },
  { value: 28, label: '3G Bilisim' },
  { value: 29, label: 'Mars Sms' },
  { value: 30, label: 'Smart Sms' },
  { value: 31, label: 'TTMESAJ' },
  { value: 32, label: 'TTMESAJ V2' },
  { value: 33, label: 'Fink SMS' },
  { value: 34, label: 'Isobil' },
  { value: 35, label: 'Isobil V2' },
];

export const splittedDefaultProviderList = [
  { value: 15, label: 'AsistBT' },
  { value: 16, label: 'Fast SMS' },
  { value: 17, label: 'Jet SMS' },
  { value: 18, label: 'Jet SMS QUERY' },
  { value: 19, label: 'Jet SMS QUERY v2' },
  { value: 20, label: 'Maradit' },
  { value: 21, label: 'Mobildev' },
  { value: 22, label: 'Mobildev v2' },
  { value: 23, label: 'Netgsm' },
  { value: 24, label: 'Posta Guvercini' },
  { value: 25, label: 'Smile SMS' },
  { value: 26, label: 'Teknomart' },
  { value: 27, label: 'Teknomart OTP' },
  { value: 28, label: '3G Bilisim' },
  { value: 29, label: 'Mars Sms' },
  { value: 30, label: 'Smart Sms' },
  { value: 31, label: 'TTMESAJ' },
  { value: 32, label: 'TTMESAJ V2' },
  { value: 33, label: 'Fink SMS' },
  { value: 34, label: 'Isobil' },
  { value: 35, label: 'Isobil V2' },
];
